### PR TITLE
Simplification of command-line arguments, and corresponding changes to examples and tests

### PR DESCRIPTION
**Pull request by karpov-sv**

### CODE REVIEW

**Comment by dcorre** [comment]
Hi @karpov-sv,

thanks again for the huge restructuring work. 

I am testing your PR and it seems that in the output result directory you do not keep the structure of the input folder. You consider only the name of the files and create a folder for each image. This can be a problem when you have many folders corresponding to different set of observation run, or nights let's say, as some image filenames can be identical as they do not belong to the same folder. 

Example:
I have an input folder like this:

data/   
---- image.fits   
---- day_0/   
-------- image.fits   

the output directory will only contain:

results/   
---- image/   
-------- image.fits and all the results   


So it will contain only one image as it skips the day_0/ subfolder. Did you make it on purpose? or can I fix it as it was before, i.e. reproducing the exact same structure as the input folder.

**Comment by dcorre** [comment]
One solution, would be to modify utils.list_files() to return not only the list of files, but also a second list containing the list of original main input directory paths for each filename (easy as it is one of the input of this function).

Then, this second list is passed to make_results_dir() which instead of using os.path.basename() to create the output dir structure, will simply remove the original folder path from the whole path. Using a string.replace('pattern', '') should do the job.

Do you have a more elegant solution?

**Comment by karpov-sv** [comment]
Ok, here is a fix for it (for now only applied to gmadet-run, not to all other use cases of list_files). 
It extracts the relative paths of every filename in respect to the folder provided on command line when scanning it recursively, so in your example it will properly create day_0 sub-folder for second image.fits. That will work if you are giving just 'data' at command-line.
But - it will not work if you are providing several dirs, e.g. 'data data2', on command line, and then they have identical files or subfolders in it - as there is no nice way to properly find subdir names in generic case (as you may also provide '/data/ /some/more/dir/with/data2' , or something even more complicated).

Still, I think it will work for now.

**Comment by dcorre** [comment]
Thanks Sergey! 

One way to solve the case of multi input folders is to keep the input folder in the path names, so actually keep the exact same structure as the inputs. Which will make it easier for the user to navigate through the results. 

I'll add it myself except if you think that this fix is not a good idea.

**Comment by karpov-sv** [comment]
What do you mean? You want to keep in the paths all the folders up to root?

**Comment by dcorre** [comment]
If you provide: data data2 data3 then in  the result folder you keep data data2 and data3 and their respective sub-folder.

If you provide only one input argument then the method you implemented is used. If you provide data, just reproduce the architecture starting one level below data/.

**Comment by dcorre** [comment]
I just added this in utils.list_files()

    if len(paths) > 1:   
        subdirs += [os.path.dirname(_) for _ in filenames_path]   
    else:
        subdirs += [os.path.dirname(os.path.relpath(_, path)) \
                           for _ in filenames_path]

**Comment by karpov-sv** [comment]
Just imagine how it will mess the things if you feed it with ../../../data2
as a second path :-)


вт, 20 окт. 2020 г. в 09:39, dcorre <notifications@github.com>:

**Comment by dcorre** [comment]
Right, I did not think about it. 

Easy fix, remove all ../ patterns in the path ;)

But if you provide the whole path from /home/... then it is a mess indeed

One better solution is to keep only the last directory from the provided path. Do you see any case that would cause a mess with this approach?

**Comment by karpov-sv** [comment]
So I suggest to just keep it as it was in my PR for now

**Comment by karpov-sv** [comment]
> One better solution is to keep only the last directory from the provided path. Do you see any case that would cause a mess with this approach?

Will start to fail if these last directories are also not unique.

The only fully fault-tolerant solution is to keep full absolute paths, starting from the root (and then maybe normalising them to a common denominator) - but I don't like it.

**Comment by dcorre** [comment]
Ok, I prefer that the code creates a structure with the name of the last directory in the result folder. It will be easier to navigate through the results. And it is easy to warn the user that the code will fail if data folder have same last directory names. 

So I will include it in your PR.

**Pull request merged**
